### ISSUE TITLE
The name Akshay gupta is now hardcoded in teh code

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/cloudmesh-javascript#39]
instead of readung the name form the profile, now the name is aksha guts, this is a bug

**Comment by laszewsk** [comment]
this use do work and is now broken

**Comment by jogoodma** [comment]
Can you point to the line of code where you are seeing this because I do not see this.  Furthermore, this code was removed last week in [this commit](https://github.com/cloudmesh/cloudmesh-javascript/commit/f9b53de6fbaca3db6bc9fcde376d9e7eef343e0a).  The change was then merged into master and develop early Friday morning.  Are you sure your repo is up to date?

**Comment by laszewsk** [comment]
ok i did an update this ne seems from an old branch  made sure i have new version hoever due to #40 i can not test

**Comment by laszewsk** [comment]
This was solved
